name: sign_workflow

# execute this workflow automatically when a release is first created by our
# 'build' workflow
on:
  repository_dispatch:
    types: [sign_release]

jobs:

  sign_job:
    runs-on: ubuntu-latest
    container: debian:buster-slim

    steps:

    - uses: actions/checkout@v2

    - name: Execute script to sign release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BUSKILL_PRERELEASE_PGP_KEY: ${{ secrets.BUSKILL_PRERELEASE_PGP_KEY }}
        RELEASE_ID: ${{ github.event.client_payload.release_id }}
      run: "build/signRelease.sh"
      shell: bash

