name: sign_workflow

# execute this workflow automatically when a release is first created by our
# 'build' workflow
on:
  repository_dispatch:
    types: [sign_release]

jobs:

  sign_job:
    runs-on: ubuntu-latest
    container: debian:buster-slim

    steps:

    - name: Query for release ID
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        RELEASE_ID=$(echo "${{ github.event.client_payload.release_id }}")
        apt-get update
        apt-get -y install curl
        (echo "${RELEASE_ID//\"}" | grep -E '^[0-9]+$') || exit 1
        curl -i --header "authorization: Bearer ${GITHUB_TOKEN}" "https://api.github.com/repos/buskill/buskill-app/releases/${RELEASE_ID}"
      shell: bash

